name: cpp

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: aminya/setup-cpp@v1
        with: 
          conan: true
          cmake: true

      - name: Build
        working-directory: ./build
        run: |
          conan install .. 
          conan build ..

      - name : Test
        working-directory: ./build
        run: 
          ctest .
